 /* ************************************************************************** */
/** Descriptive File Name

  @Company
    Company Name

  @File Name
    filename.c

  @Summary
    Brief description of the file.

  @Description
    Describe the purpose of this file.
 */
/* ************************************************************************** */

/* ************************************************************************** */
/* ************************************************************************** */
/* Section: Included Files                                                    */
/* ************************************************************************** */
/* ************************************************************************** */

/* This section lists the other files that are included in this file.
 */

/* TODO:  Include other files here if needed. */

#include "definitions.h"                // SYS function prototypes
#include "i2c_address.h"
#include "Purnell_OEM.h"
#include "pmbus_command.h"
#include <stdio.h>
#include <string.h>

uint8_t PSU0_PMBUS_PAGE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_CAPABILITY_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_MODE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_FAN_CONFIG_12_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_FAN_COMMAND_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_OC_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_OC_WARNING_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_OT_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IIN_OC_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_POUT_OP_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PIN_OP_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_WORD_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_VOUT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_IOUT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_INPUT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_TEMPERATURE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_CML_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_MFR_SPECIFIC_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_FANS_1_2_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_VIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_IIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_VOUT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_IOUT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_TEMPERATURE_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_TEMPERATURE_2_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_TEMPERATURE_2_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_FAN_SPEED_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_POUT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_PIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_VIN_MIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_VIN_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_IIN_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_PIN_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_VOUT_MIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_VOUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_IOUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_POUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_MAX_TEMP_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_MAX_TEMP_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_CLEAR_FAULTS_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_OPERATION_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_ON_OFF_CONFIG_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_PHASE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_WRITE_PROTECT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_QUERY_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_SMBALERT_MASK_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_COMMAND_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_TRIM_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_CAL_OFFSET_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_MARGIN_HIGH_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_MARGIN_LOW_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_TRANSITION_RATE_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_DROOP_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_SCALE_LOOP_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_SCALE_MONITOR_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_COEFFICIENTS_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_POUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_FAN_COMMAND_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_FAN_CONFIG_34_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_FAN_COMMAND_3_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_FAN_COMMAND_4_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_OV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_OV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_OV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_UV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_UV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VOUT_UV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_OC_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_OC_LV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_OC_LV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_UC_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IOUT_UC_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_OT_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_OT_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_UT_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_UT_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_UT_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VIN_OV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VIN_OV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VIN_OV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VIN_UV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_VIN_UV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IIN_OC_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_POUT_OP_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_BYTE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_OTHER_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_STATUS_FAN_34_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_VCAP_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_FAN_SPEED_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_FAN_SPEED_3_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_FAN_SPEED_4_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_DUTY_CYCLE_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_FREQUENCY_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_REVISION_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_MFR_ID_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_MFR_MODEL_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_MFR_REVISION_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_MFR_LOCATION_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_MFR_DATE_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PMBUS_MFR_SERIAL_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IC_DEVICE_ID_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_IC_DEVICE_REV_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_MFR_MAX_TEMP_3_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_PAGE_PLUS_WRITE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_EIN_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU0_READ_EOUT_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};


uint8_t PSU1_PMBUS_PAGE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_CAPABILITY_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_MODE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_FAN_CONFIG_12_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_FAN_COMMAND_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_OC_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_OC_WARNING_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_OT_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IIN_OC_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_POUT_OP_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PIN_OP_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_WORD_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_VOUT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_IOUT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_INPUT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_TEMPERATURE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_CML_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_MFR_SPECIFIC_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_FANS_1_2_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_VIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_IIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_VOUT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_IOUT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_TEMPERATURE_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_TEMPERATURE_2_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_TEMPERATURE_2_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_FAN_SPEED_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_POUT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_PIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_VIN_MIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_VIN_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_IIN_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_PIN_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_VOUT_MIN_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_VOUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_IOUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_POUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_MAX_TEMP_1_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_MAX_TEMP_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_CLEAR_FAULTS_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_OPERATION_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_ON_OFF_CONFIG_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_PHASE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_WRITE_PROTECT_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_QUERY_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_SMBALERT_MASK_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_COMMAND_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_TRIM_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_CAL_OFFSET_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_MARGIN_HIGH_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_MARGIN_LOW_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_TRANSITION_RATE_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_DROOP_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_SCALE_LOOP_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_SCALE_MONITOR_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_COEFFICIENTS_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_POUT_MAX_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_FAN_COMMAND_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_FAN_CONFIG_34_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_FAN_COMMAND_3_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_FAN_COMMAND_4_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_OV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_OV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_OV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_UV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_UV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VOUT_UV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_OC_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_OC_LV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_OC_LV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_UC_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IOUT_UC_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_OT_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_OT_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_UT_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_UT_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_UT_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VIN_OV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VIN_OV_FAULT_RESPONSE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VIN_OV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VIN_UV_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_VIN_UV_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IIN_OC_FAULT_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_POUT_OP_WARN_LIMIT_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_BYTE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_OTHER_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_STATUS_FAN_34_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_VCAP_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_FAN_SPEED_2_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_FAN_SPEED_3_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_FAN_SPEED_4_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_DUTY_CYCLE_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_FREQUENCY_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_REVISION_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_MFR_ID_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_MFR_MODEL_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_MFR_REVISION_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_MFR_LOCATION_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_MFR_DATE_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PMBUS_MFR_SERIAL_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IC_DEVICE_ID_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_IC_DEVICE_REV_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_MFR_MAX_TEMP_3_Data[PMBUS_THREE_SIZE_BYTES] = {[0 ... (PMBUS_THREE_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_PAGE_PLUS_WRITE_Data[PMBUS_TWO_SIZE_BYTES] = {[0 ... (PMBUS_TWO_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_EIN_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};
uint8_t PSU1_READ_EOUT_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};

uint8_t PSU_PMbus_Data[PMBUS_SIX_SIZE_BYTES] = {[0 ... (PMBUS_SIX_SIZE_BYTES-1)] = UN_PMBUS_STATUS};

//extern volatile struct KeyValue * volatile PSU_data_array;
KeyValue PSU0_DataArrayPtr[] = {{PSU0_PMBUS_PAGE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_VOUT_MODE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_FAN_CONFIG_12_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_FAN_COMMAND_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_IOUT_OC_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_IOUT_OC_WARNING_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU0_OT_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_IIN_OC_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_POUT_OP_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_PIN_OP_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_STATUS_WORD_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_STATUS_VOUT_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_IOUT_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_INPUT_Data,PMBUS_TWO_SIZE_BYTES}, 
{PSU0_STATUS_TEMPERATURE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_CML_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_MFR_SPECIFIC_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_FANS_1_2_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_READ_VIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_IIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_VOUT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_IOUT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_TEMPERATURE_1_Data,PMBUS_THREE_SIZE_BYTES},
{PSU0_READ_TEMPERATURE_2_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_TEMPERATURE_2_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_FAN_SPEED_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_POUT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_PIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_VIN_MIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_VIN_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_IIN_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_PIN_MAX_Data,PMBUS_THREE_SIZE_BYTES},
{PSU0_MFR_VOUT_MIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_VOUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_IOUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_POUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_MAX_TEMP_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_MFR_MAX_TEMP_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_PMBUS_OPERATION_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_PMBUS_ON_OFF_CONFIG_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_PMBUS_PHASE_Data,PMBUS_TWO_SIZE_BYTES},
{PSU0_PMBUS_WRITE_PROTECT_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_PMBUS_QUERY_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_PMBUS_SMBALERT_MASK_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_COMMAND_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_TRIM_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_CAL_OFFSET_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_MARGIN_HIGH_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_MARGIN_LOW_Data,PMBUS_THREE_SIZE_BYTES},
{PSU0_VOUT_TRANSITION_RATE_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_DROOP_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_SCALE_LOOP_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_SCALE_MONITOR_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_PMBUS_COEFFICIENTS_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_POUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_FAN_COMMAND_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_FAN_CONFIG_34_Data,PMBUS_TWO_SIZE_BYTES}, 
{PSU0_FAN_COMMAND_3_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_FAN_COMMAND_4_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_OV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_OV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_VOUT_OV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_UV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_UV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VOUT_UV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, 
{PSU0_IOUT_OC_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_IOUT_OC_LV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_IOUT_OC_LV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_IOUT_UC_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_IOUT_UC_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_OT_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_OT_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_UT_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU0_UT_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_UT_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_VIN_OV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VIN_OV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_VIN_OV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VIN_UV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_VIN_UV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_IIN_OC_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU0_POUT_OP_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_STATUS_BYTE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_OTHER_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_STATUS_FAN_34_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_READ_VCAP_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_FAN_SPEED_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_FAN_SPEED_3_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_FAN_SPEED_4_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_DUTY_CYCLE_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU0_READ_FREQUENCY_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_PMBUS_REVISION_Data,PMBUS_TWO_SIZE_BYTES}, {PSU0_PMBUS_MFR_ID_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_PMBUS_MFR_MODEL_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_PMBUS_MFR_REVISION_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_PMBUS_MFR_LOCATION_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_PMBUS_MFR_DATE_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_PMBUS_MFR_SERIAL_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_IC_DEVICE_ID_Data,PMBUS_SIX_SIZE_BYTES}, 
{PSU0_IC_DEVICE_REV_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_MFR_MAX_TEMP_3_Data,PMBUS_THREE_SIZE_BYTES}, {PSU0_READ_EIN_Data,PMBUS_SIX_SIZE_BYTES}, {PSU0_READ_EOUT_Data,PMBUS_SIX_SIZE_BYTES}};
//No PSU0_PAGE_PLUS_WRITE_Data Command
//PSU0_CAPABILITY_Data hard code as 30

KeyValue PSU1_DataArrayPtr[] = {{PSU1_PMBUS_PAGE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_VOUT_MODE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_FAN_CONFIG_12_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_FAN_COMMAND_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_IOUT_OC_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_IOUT_OC_WARNING_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU1_OT_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_IIN_OC_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_POUT_OP_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_PIN_OP_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_STATUS_WORD_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_STATUS_VOUT_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_IOUT_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_INPUT_Data,PMBUS_TWO_SIZE_BYTES}, 
{PSU1_STATUS_TEMPERATURE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_CML_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_MFR_SPECIFIC_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_FANS_1_2_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_READ_VIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_IIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_VOUT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_IOUT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_TEMPERATURE_1_Data,PMBUS_THREE_SIZE_BYTES},
{PSU1_READ_TEMPERATURE_2_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_TEMPERATURE_2_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_FAN_SPEED_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_POUT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_PIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_VIN_MIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_VIN_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_IIN_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_PIN_MAX_Data,PMBUS_THREE_SIZE_BYTES},
{PSU1_MFR_VOUT_MIN_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_VOUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_IOUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_POUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_MAX_TEMP_1_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_MFR_MAX_TEMP_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_PMBUS_OPERATION_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_PMBUS_ON_OFF_CONFIG_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_PMBUS_PHASE_Data,PMBUS_TWO_SIZE_BYTES},
{PSU1_PMBUS_WRITE_PROTECT_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_PMBUS_QUERY_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_PMBUS_SMBALERT_MASK_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_COMMAND_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_TRIM_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_CAL_OFFSET_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_MARGIN_HIGH_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_MARGIN_LOW_Data,PMBUS_THREE_SIZE_BYTES},
{PSU1_VOUT_TRANSITION_RATE_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_DROOP_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_SCALE_LOOP_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_SCALE_MONITOR_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_PMBUS_COEFFICIENTS_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_POUT_MAX_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_FAN_COMMAND_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_FAN_CONFIG_34_Data,PMBUS_TWO_SIZE_BYTES}, 
{PSU1_FAN_COMMAND_3_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_FAN_COMMAND_4_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_OV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_OV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_VOUT_OV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_UV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_UV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VOUT_UV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, 
{PSU1_IOUT_OC_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_IOUT_OC_LV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_IOUT_OC_LV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_IOUT_UC_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_IOUT_UC_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_OT_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_OT_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_UT_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU1_UT_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_UT_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_VIN_OV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VIN_OV_FAULT_RESPONSE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_VIN_OV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VIN_UV_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_VIN_UV_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_IIN_OC_FAULT_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU1_POUT_OP_WARN_LIMIT_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_STATUS_BYTE_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_OTHER_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_STATUS_FAN_34_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_READ_VCAP_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_FAN_SPEED_2_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_FAN_SPEED_3_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_FAN_SPEED_4_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_DUTY_CYCLE_Data,PMBUS_THREE_SIZE_BYTES}, 
{PSU1_READ_FREQUENCY_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_PMBUS_REVISION_Data,PMBUS_TWO_SIZE_BYTES}, {PSU1_PMBUS_MFR_ID_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_PMBUS_MFR_MODEL_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_PMBUS_MFR_REVISION_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_PMBUS_MFR_LOCATION_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_PMBUS_MFR_DATE_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_PMBUS_MFR_SERIAL_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_IC_DEVICE_ID_Data,PMBUS_SIX_SIZE_BYTES}, 
{PSU1_IC_DEVICE_REV_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_MFR_MAX_TEMP_3_Data,PMBUS_THREE_SIZE_BYTES}, {PSU1_READ_EIN_Data,PMBUS_SIX_SIZE_BYTES}, {PSU1_READ_EOUT_Data,PMBUS_SIX_SIZE_BYTES}};
//No PSU1_PAGE_PLUS_WRITE_Data Command
//PSU1_CAPABILITY_Data hard code as 30

void Read_PSU0_PMbus_Data(DataMap *PSU)
{
    uint32_t PMbuswrLength = 1;
    uint32_t PMbusrdLength = PMBUS_SIX_SIZE_BYTES;

    uint8_t PMBUS_PAGE_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_PAGE};
    uint8_t PMBUS_OPERATION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_OPERATION};
    uint8_t PMBUS_ON_OFF_CONFIG_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_ON_OFF_CONFIG};
    uint8_t PMBUS_PHASE_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_PHASE};
    uint8_t PMBUS_WRITE_PROTECT_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_WRITE_PROTECT};     
    uint8_t VOUT_MODE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MODE};
    uint8_t FAN_CONFIG_12_CMD[CMD_SIZE_ONE_BYTE] = {FAN_CONFIG_12};          
    uint8_t FAN_COMMAND_1_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_1};          
    uint8_t IOUT_OC_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_FAULT_LIMIT};
    uint8_t IOUT_OC_WARNING_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_WARNING_LIMIT};
    uint8_t OT_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {OT_WARN_LIMIT};
    uint8_t IIN_OC_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IIN_OC_WARN_LIMIT};
    uint8_t POUT_OP_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {POUT_OP_FAULT_LIMIT};
    uint8_t PIN_OP_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {PIN_OP_WARN_LIMIT};
    uint8_t STATUS_WORD_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_WORD};
    uint8_t STATUS_VOUT_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_VOUT};
    uint8_t STATUS_IOUT_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_IOUT};
    uint8_t STATUS_INPUT_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_INPUT};
    uint8_t STATUS_TEMPERATURE_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_TEMPERATURE};
    uint8_t STATUS_CML_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_CML};
    uint8_t STATUS_MFR_SPECIFIC_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_MFR_SPECIFIC};
    uint8_t STATUS_FANS_1_2_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_FANS_1_2};
    uint8_t READ_EIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_EIN};
    uint8_t READ_EOUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_EOUT};
    uint8_t READ_VIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_VIN};
    uint8_t READ_IIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_IIN};
    uint8_t READ_VOUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_VOUT};
    uint8_t READ_IOUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_IOUT};
    uint8_t READ_TEMPERATURE_1_CMD[CMD_SIZE_ONE_BYTE] = {READ_TEMPERATURE_1};
    uint8_t READ_TEMPERATURE_2_1_CMD[CMD_SIZE_ONE_BYTE] = {READ_TEMPERATURE_2_1};
    uint8_t READ_TEMPERATURE_2_2_CMD[CMD_SIZE_ONE_BYTE] = {READ_TEMPERATURE_2_2};
    uint8_t READ_FAN_SPEED_1_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_1};
    uint8_t READ_POUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_POUT};
    uint8_t READ_PIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_PIN};
    uint8_t MFR_VIN_MIN_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VIN_MIN};
    uint8_t MFR_VIN_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VIN_MAX};
    uint8_t MFR_IIN_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_IIN_MAX};
    uint8_t MFR_PIN_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_PIN_MAX};
    uint8_t MFR_VOUT_MIN_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VOUT_MIN};
    uint8_t MFR_VOUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VOUT_MAX};
    uint8_t MFR_IOUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_IOUT_MAX};
    uint8_t MFR_POUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_POUT_MAX};
    uint8_t MFR_MAX_TEMP_1_CMD[CMD_SIZE_ONE_BYTE] = {MFR_MAX_TEMP_1};
    uint8_t MFR_MAX_TEMP_2_CMD[CMD_SIZE_ONE_BYTE] = {MFR_MAX_TEMP_2};

    uint8_t PMBUS_QUERY_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_QUERY};
    uint8_t PMBUS_SMBALERT_MASK_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_SMBALERT_MASK};
    uint8_t VOUT_COMMAND_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_COMMAND};
    uint8_t VOUT_TRIM_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_TRIM};
    uint8_t VOUT_CAL_OFFSET_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_CAL_OFFSET};
    uint8_t VOUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MAX};
    uint8_t VOUT_MARGIN_HIGH_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MARGIN_HIGH};
    uint8_t VOUT_MARGIN_LOW_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MARGIN_LOW};
    uint8_t VOUT_TRANSITION_RATE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_TRANSITION_RATE};
    uint8_t VOUT_DROOP_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_DROOP};
    uint8_t VOUT_SCALE_LOOP_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_SCALE_LOOP};
    uint8_t VOUT_SCALE_MONITOR_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_SCALE_MONITOR};
    uint8_t PMBUS_COEFFICIENTS_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_COEFFICIENTS};
    uint8_t POUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {POUT_MAX};
    uint8_t FAN_COMMAND_2_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_2};
    uint8_t FAN_CONFIG_34_CMD[CMD_SIZE_ONE_BYTE] = {FAN_CONFIG_34};
    uint8_t FAN_COMMAND_3_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_3};
    uint8_t FAN_COMMAND_4_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_4};
    uint8_t VOUT_OV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_OV_FAULT_LIMIT};
    uint8_t VOUT_OV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_OV_FAULT_RESPONSE};
    uint8_t VOUT_OV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_OV_WARN_LIMIT};
    uint8_t VOUT_UV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_UV_WARN_LIMIT};
    uint8_t VOUT_UV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_UV_FAULT_LIMIT};
    uint8_t VOUT_UV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_UV_FAULT_RESPONSE};
    uint8_t IOUT_OC_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_FAULT_RESPONSE};
    uint8_t IOUT_OC_LV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_LV_FAULT_LIMIT};
    uint8_t IOUT_OC_LV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_LV_FAULT_RESPONSE};
    uint8_t IOUT_UC_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_UC_FAULT_LIMIT};
    uint8_t IOUT_UC_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_UC_FAULT_RESPONSE};
    uint8_t OT_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {OT_FAULT_LIMIT};
    uint8_t OT_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {OT_FAULT_RESPONSE};
    uint8_t UT_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {UT_WARN_LIMIT};
    uint8_t UT_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {UT_FAULT_LIMIT};
    uint8_t UT_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {UT_FAULT_RESPONSE};
    uint8_t VIN_OV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_OV_FAULT_LIMIT};
    uint8_t VIN_OV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {VIN_OV_FAULT_RESPONSE};
    uint8_t VIN_OV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_OV_WARN_LIMIT};
    uint8_t VIN_UV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_UV_WARN_LIMIT};
    uint8_t VIN_UV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_UV_FAULT_LIMIT};
    uint8_t IIN_OC_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IIN_OC_FAULT_LIMIT};
    uint8_t POUT_OP_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {POUT_OP_WARN_LIMIT};
    uint8_t STATUS_BYTE_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_BYTE};
    uint8_t STATUS_OTHER_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_OTHER};
    uint8_t STATUS_FAN_34_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_FAN_34};
    uint8_t READ_VCAP_CMD[CMD_SIZE_ONE_BYTE] = {READ_VCAP};
    uint8_t READ_FAN_SPEED_2_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_2};
    uint8_t READ_FAN_SPEED_3_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_3};
    uint8_t READ_FAN_SPEED_4_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_4};
    uint8_t READ_DUTY_CYCLE_CMD[CMD_SIZE_ONE_BYTE] = {READ_DUTY_CYCLE};
    uint8_t READ_FREQUENCY_CMD[CMD_SIZE_ONE_BYTE] = {READ_FREQUENCY};
    uint8_t PMBUS_REVISION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_REVISION};
    uint8_t PMBUS_MFR_ID_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_ID};
    uint8_t PMBUS_MFR_MODEL_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_MODEL};
    uint8_t PMBUS_MFR_REVISION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_REVISION};
    uint8_t PMBUS_MFR_LOCATION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_LOCATION};
    uint8_t PMBUS_MFR_DATE_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_DATE};
    uint8_t PMBUS_MFR_SERIAL_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_SERIAL};
    uint8_t IC_DEVICE_ID_CMD[CMD_SIZE_ONE_BYTE] = {IC_DEVICE_ID};
    uint8_t IC_DEVICE_REV_CMD[CMD_SIZE_ONE_BYTE] = {IC_DEVICE_REV};
    uint8_t MFR_MAX_TEMP_3_CMD[CMD_SIZE_ONE_BYTE] = {MFR_MAX_TEMP_3};

    uint8_t* CmdArrayPtr[] = {PMBUS_PAGE_CMD, VOUT_MODE_CMD, FAN_CONFIG_12_CMD, FAN_COMMAND_1_CMD, IOUT_OC_FAULT_LIMIT_CMD, IOUT_OC_WARNING_LIMIT_CMD, OT_WARN_LIMIT_CMD, IIN_OC_WARN_LIMIT_CMD, POUT_OP_FAULT_LIMIT_CMD, PIN_OP_WARN_LIMIT_CMD, STATUS_WORD_CMD, 
    STATUS_VOUT_CMD, STATUS_IOUT_CMD, STATUS_INPUT_CMD, STATUS_TEMPERATURE_CMD, STATUS_CML_CMD, STATUS_MFR_SPECIFIC_CMD, STATUS_FANS_1_2_CMD, READ_VIN_CMD, READ_IIN_CMD, READ_VOUT_CMD, READ_IOUT_CMD, READ_TEMPERATURE_1_CMD, READ_TEMPERATURE_2_1_CMD, READ_TEMPERATURE_2_2_CMD, 
    READ_FAN_SPEED_1_CMD, READ_POUT_CMD, READ_PIN_CMD, MFR_VIN_MIN_CMD, MFR_VIN_MAX_CMD, MFR_IIN_MAX_CMD, MFR_PIN_MAX_CMD, MFR_VOUT_MIN_CMD, MFR_VOUT_MAX_CMD, MFR_IOUT_MAX_CMD, MFR_POUT_MAX_CMD, MFR_MAX_TEMP_1_CMD, MFR_MAX_TEMP_2_CMD, PMBUS_OPERATION_CMD, PMBUS_ON_OFF_CONFIG_CMD, 
    PMBUS_PHASE_CMD, PMBUS_WRITE_PROTECT_CMD, PMBUS_QUERY_CMD, PMBUS_SMBALERT_MASK_CMD, VOUT_COMMAND_CMD, VOUT_TRIM_CMD, VOUT_CAL_OFFSET_CMD, VOUT_MAX_CMD, VOUT_MARGIN_HIGH_CMD, VOUT_MARGIN_LOW_CMD, VOUT_TRANSITION_RATE_CMD, VOUT_DROOP_CMD, VOUT_SCALE_LOOP_CMD, VOUT_SCALE_MONITOR_CMD, 
    PMBUS_COEFFICIENTS_CMD, POUT_MAX_CMD, FAN_COMMAND_2_CMD, FAN_CONFIG_34_CMD, FAN_COMMAND_3_CMD, FAN_COMMAND_4_CMD, VOUT_OV_FAULT_LIMIT_CMD, VOUT_OV_FAULT_RESPONSE_CMD, VOUT_OV_WARN_LIMIT_CMD, VOUT_UV_WARN_LIMIT_CMD, VOUT_UV_FAULT_LIMIT_CMD, VOUT_UV_FAULT_RESPONSE_CMD, IOUT_OC_FAULT_RESPONSE_CMD, 
    IOUT_OC_LV_FAULT_LIMIT_CMD, IOUT_OC_LV_FAULT_RESPONSE_CMD, IOUT_UC_FAULT_LIMIT_CMD, IOUT_UC_FAULT_RESPONSE_CMD, OT_FAULT_LIMIT_CMD, OT_FAULT_RESPONSE_CMD, UT_WARN_LIMIT_CMD, UT_FAULT_LIMIT_CMD, UT_FAULT_RESPONSE_CMD, VIN_OV_FAULT_LIMIT_CMD, VIN_OV_FAULT_RESPONSE_CMD, VIN_OV_WARN_LIMIT_CMD, 
    VIN_UV_WARN_LIMIT_CMD, VIN_UV_FAULT_LIMIT_CMD, IIN_OC_FAULT_LIMIT_CMD, POUT_OP_WARN_LIMIT_CMD, STATUS_BYTE_CMD, STATUS_OTHER_CMD, STATUS_FAN_34_CMD, READ_VCAP_CMD, READ_FAN_SPEED_2_CMD, READ_FAN_SPEED_3_CMD, READ_FAN_SPEED_4_CMD, READ_DUTY_CYCLE_CMD, READ_FREQUENCY_CMD, PMBUS_REVISION_CMD, 
    PMBUS_MFR_ID_CMD, PMBUS_MFR_MODEL_CMD, PMBUS_MFR_REVISION_CMD, PMBUS_MFR_LOCATION_CMD, PMBUS_MFR_DATE_CMD, PMBUS_MFR_SERIAL_CMD, IC_DEVICE_ID_CMD, IC_DEVICE_REV_CMD, MFR_MAX_TEMP_3_CMD, READ_EIN_CMD, READ_EOUT_CMD};    

    PSU0_CAPABILITY_Data[0] = 30;
    PSU0_CLEAR_FAULTS_Data[0] = CLEAR_FAULTS;
    PSU0_CLEAR_FAULTS_Data[1] = CLEAR_FAULTS;
    PSU0_PAGE_PLUS_WRITE_Data[0] = PAGE_PLUS_WRITE;
    PSU0_PAGE_PLUS_WRITE_Data[1] = PAGE_PLUS_WRITE;
    for (size_t i = 0; i < sizeof( CmdArrayPtr )/sizeof( CmdArrayPtr[0] ) ; i++ ) {       
        SERCOM0_I2C_WriteRead( PSU0_PMBUS_ADDR , (uint8_t*)CmdArrayPtr[i], PMbuswrLength , PSU_PMbus_Data , PMbusrdLength);
        while (SERCOM0_I2C_IsBusy( ));
        memcpy(PSU0_DataArrayPtr[i].key, PSU_PMbus_Data, PSU0_DataArrayPtr[i].value);
        PSU->psu1_table[CmdArrayPtr[i][0]].key = PSU0_DataArrayPtr[i].key;
        PSU->psu1_table[CmdArrayPtr[i][0]].cmd = CmdArrayPtr[i][0];
        memset(PSU_PMbus_Data, UN_PMBUS_STATUS, sizeof(PSU_PMbus_Data));
        if (CmdArrayPtr[i][0] == 0x8d || CmdArrayPtr[i][0] == 0x8e || CmdArrayPtr[i][0] == 0x8f)
        {
            printf("PDB I2C Master RW PSU1 temp command : 0x%x , data Byte 0: 0x%x, data Byte 1: 0x%x  \r\n", CmdArrayPtr[i][0], PSU->psu1_table[CmdArrayPtr[i][0]].key[0], PSU->psu1_table[CmdArrayPtr[i][0]].key[1]);
        }
    }
    PSU->psu1_table[CAPABILITY].key = PSU0_CAPABILITY_Data;
    PSU->psu1_table[CLEAR_FAULTS].key = PSU0_CLEAR_FAULTS_Data;
    PSU->psu1_table[PAGE_PLUS_WRITE].key = PSU0_PAGE_PLUS_WRITE_Data;
    PSU->psu1_table[CAPABILITY].cmd = CAPABILITY;
    PSU->psu1_table[CLEAR_FAULTS].cmd = CLEAR_FAULTS;
    PSU->psu1_table[PAGE_PLUS_WRITE].cmd = PAGE_PLUS_WRITE;
}

void Read_PSU1_PMbus_Data(DataMap *PSU)
{
    uint32_t PMbuswrLength = 1;
    uint32_t PMbusrdLength = PMBUS_SIX_SIZE_BYTES;

    uint8_t PMBUS_PAGE_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_PAGE};
    uint8_t PMBUS_OPERATION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_OPERATION};
    uint8_t PMBUS_ON_OFF_CONFIG_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_ON_OFF_CONFIG};
    uint8_t PMBUS_PHASE_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_PHASE};
    uint8_t PMBUS_WRITE_PROTECT_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_WRITE_PROTECT};     
    uint8_t VOUT_MODE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MODE};
    uint8_t FAN_CONFIG_12_CMD[CMD_SIZE_ONE_BYTE] = {FAN_CONFIG_12};          
    uint8_t FAN_COMMAND_1_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_1};          
    uint8_t IOUT_OC_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_FAULT_LIMIT};
    uint8_t IOUT_OC_WARNING_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_WARNING_LIMIT};
    uint8_t OT_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {OT_WARN_LIMIT};
    uint8_t IIN_OC_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IIN_OC_WARN_LIMIT};
    uint8_t POUT_OP_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {POUT_OP_FAULT_LIMIT};
    uint8_t PIN_OP_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {PIN_OP_WARN_LIMIT};
    uint8_t STATUS_WORD_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_WORD};
    uint8_t STATUS_VOUT_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_VOUT};
    uint8_t STATUS_IOUT_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_IOUT};
    uint8_t STATUS_INPUT_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_INPUT};
    uint8_t STATUS_TEMPERATURE_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_TEMPERATURE};
    uint8_t STATUS_CML_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_CML};
    uint8_t STATUS_MFR_SPECIFIC_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_MFR_SPECIFIC};
    uint8_t STATUS_FANS_1_2_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_FANS_1_2};
    uint8_t READ_EIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_EIN};
    uint8_t READ_EOUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_EOUT};
    uint8_t READ_VIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_VIN};
    uint8_t READ_IIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_IIN};
    uint8_t READ_VOUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_VOUT};
    uint8_t READ_IOUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_IOUT};
    uint8_t READ_TEMPERATURE_1_CMD[CMD_SIZE_ONE_BYTE] = {READ_TEMPERATURE_1};
    uint8_t READ_TEMPERATURE_2_1_CMD[CMD_SIZE_ONE_BYTE] = {READ_TEMPERATURE_2_1};
    uint8_t READ_TEMPERATURE_2_2_CMD[CMD_SIZE_ONE_BYTE] = {READ_TEMPERATURE_2_2};
    uint8_t READ_FAN_SPEED_1_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_1};
    uint8_t READ_POUT_CMD[CMD_SIZE_ONE_BYTE] = {READ_POUT};
    uint8_t READ_PIN_CMD[CMD_SIZE_ONE_BYTE] = {READ_PIN};
    uint8_t MFR_VIN_MIN_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VIN_MIN};
    uint8_t MFR_VIN_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VIN_MAX};
    uint8_t MFR_IIN_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_IIN_MAX};
    uint8_t MFR_PIN_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_PIN_MAX};
    uint8_t MFR_VOUT_MIN_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VOUT_MIN};
    uint8_t MFR_VOUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_VOUT_MAX};
    uint8_t MFR_IOUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_IOUT_MAX};
    uint8_t MFR_POUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {MFR_POUT_MAX};
    uint8_t MFR_MAX_TEMP_1_CMD[CMD_SIZE_ONE_BYTE] = {MFR_MAX_TEMP_1};
    uint8_t MFR_MAX_TEMP_2_CMD[CMD_SIZE_ONE_BYTE] = {MFR_MAX_TEMP_2};

    uint8_t PMBUS_QUERY_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_QUERY};
    uint8_t PMBUS_SMBALERT_MASK_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_SMBALERT_MASK};
    uint8_t VOUT_COMMAND_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_COMMAND};
    uint8_t VOUT_TRIM_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_TRIM};
    uint8_t VOUT_CAL_OFFSET_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_CAL_OFFSET};
    uint8_t VOUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MAX};
    uint8_t VOUT_MARGIN_HIGH_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MARGIN_HIGH};
    uint8_t VOUT_MARGIN_LOW_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_MARGIN_LOW};
    uint8_t VOUT_TRANSITION_RATE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_TRANSITION_RATE};
    uint8_t VOUT_DROOP_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_DROOP};
    uint8_t VOUT_SCALE_LOOP_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_SCALE_LOOP};
    uint8_t VOUT_SCALE_MONITOR_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_SCALE_MONITOR};
    uint8_t PMBUS_COEFFICIENTS_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_COEFFICIENTS};
    uint8_t POUT_MAX_CMD[CMD_SIZE_ONE_BYTE] = {POUT_MAX};
    uint8_t FAN_COMMAND_2_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_2};
    uint8_t FAN_CONFIG_34_CMD[CMD_SIZE_ONE_BYTE] = {FAN_CONFIG_34};
    uint8_t FAN_COMMAND_3_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_3};
    uint8_t FAN_COMMAND_4_CMD[CMD_SIZE_ONE_BYTE] = {FAN_COMMAND_4};
    uint8_t VOUT_OV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_OV_FAULT_LIMIT};
    uint8_t VOUT_OV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_OV_FAULT_RESPONSE};
    uint8_t VOUT_OV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_OV_WARN_LIMIT};
    uint8_t VOUT_UV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_UV_WARN_LIMIT};
    uint8_t VOUT_UV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_UV_FAULT_LIMIT};
    uint8_t VOUT_UV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {VOUT_UV_FAULT_RESPONSE};
    uint8_t IOUT_OC_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_FAULT_RESPONSE};
    uint8_t IOUT_OC_LV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_LV_FAULT_LIMIT};
    uint8_t IOUT_OC_LV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_OC_LV_FAULT_RESPONSE};
    uint8_t IOUT_UC_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_UC_FAULT_LIMIT};
    uint8_t IOUT_UC_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {IOUT_UC_FAULT_RESPONSE};
    uint8_t OT_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {OT_FAULT_LIMIT};
    uint8_t OT_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {OT_FAULT_RESPONSE};
    uint8_t UT_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {UT_WARN_LIMIT};
    uint8_t UT_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {UT_FAULT_LIMIT};
    uint8_t UT_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {UT_FAULT_RESPONSE};
    uint8_t VIN_OV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_OV_FAULT_LIMIT};
    uint8_t VIN_OV_FAULT_RESPONSE_CMD[CMD_SIZE_ONE_BYTE] = {VIN_OV_FAULT_RESPONSE};
    uint8_t VIN_OV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_OV_WARN_LIMIT};
    uint8_t VIN_UV_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_UV_WARN_LIMIT};
    uint8_t VIN_UV_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {VIN_UV_FAULT_LIMIT};
    uint8_t IIN_OC_FAULT_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {IIN_OC_FAULT_LIMIT};
    uint8_t POUT_OP_WARN_LIMIT_CMD[CMD_SIZE_ONE_BYTE] = {POUT_OP_WARN_LIMIT};
    uint8_t STATUS_BYTE_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_BYTE};
    uint8_t STATUS_OTHER_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_OTHER};
    uint8_t STATUS_FAN_34_CMD[CMD_SIZE_ONE_BYTE] = {STATUS_FAN_34};
    uint8_t READ_VCAP_CMD[CMD_SIZE_ONE_BYTE] = {READ_VCAP};
    uint8_t READ_FAN_SPEED_2_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_2};
    uint8_t READ_FAN_SPEED_3_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_3};
    uint8_t READ_FAN_SPEED_4_CMD[CMD_SIZE_ONE_BYTE] = {READ_FAN_SPEED_4};
    uint8_t READ_DUTY_CYCLE_CMD[CMD_SIZE_ONE_BYTE] = {READ_DUTY_CYCLE};
    uint8_t READ_FREQUENCY_CMD[CMD_SIZE_ONE_BYTE] = {READ_FREQUENCY};
    uint8_t PMBUS_REVISION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_REVISION};
    uint8_t PMBUS_MFR_ID_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_ID};
    uint8_t PMBUS_MFR_MODEL_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_MODEL};
    uint8_t PMBUS_MFR_REVISION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_REVISION};
    uint8_t PMBUS_MFR_LOCATION_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_LOCATION};
    uint8_t PMBUS_MFR_DATE_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_DATE};
    uint8_t PMBUS_MFR_SERIAL_CMD[CMD_SIZE_ONE_BYTE] = {PMBUS_MFR_SERIAL};
    uint8_t IC_DEVICE_ID_CMD[CMD_SIZE_ONE_BYTE] = {IC_DEVICE_ID};
    uint8_t IC_DEVICE_REV_CMD[CMD_SIZE_ONE_BYTE] = {IC_DEVICE_REV};
    uint8_t MFR_MAX_TEMP_3_CMD[CMD_SIZE_ONE_BYTE] = {MFR_MAX_TEMP_3};
    
    uint8_t* CmdArrayPtr[] = {PMBUS_PAGE_CMD, VOUT_MODE_CMD, FAN_CONFIG_12_CMD, FAN_COMMAND_1_CMD, IOUT_OC_FAULT_LIMIT_CMD, IOUT_OC_WARNING_LIMIT_CMD, OT_WARN_LIMIT_CMD, IIN_OC_WARN_LIMIT_CMD, POUT_OP_FAULT_LIMIT_CMD, PIN_OP_WARN_LIMIT_CMD, STATUS_WORD_CMD, 
    STATUS_VOUT_CMD, STATUS_IOUT_CMD, STATUS_INPUT_CMD, STATUS_TEMPERATURE_CMD, STATUS_CML_CMD, STATUS_MFR_SPECIFIC_CMD, STATUS_FANS_1_2_CMD, READ_VIN_CMD, READ_IIN_CMD, READ_VOUT_CMD, READ_IOUT_CMD, READ_TEMPERATURE_1_CMD, READ_TEMPERATURE_2_1_CMD, READ_TEMPERATURE_2_2_CMD, 
    READ_FAN_SPEED_1_CMD, READ_POUT_CMD, READ_PIN_CMD, MFR_VIN_MIN_CMD, MFR_VIN_MAX_CMD, MFR_IIN_MAX_CMD, MFR_PIN_MAX_CMD, MFR_VOUT_MIN_CMD, MFR_VOUT_MAX_CMD, MFR_IOUT_MAX_CMD, MFR_POUT_MAX_CMD, MFR_MAX_TEMP_1_CMD, MFR_MAX_TEMP_2_CMD, PMBUS_OPERATION_CMD, PMBUS_ON_OFF_CONFIG_CMD, 
    PMBUS_PHASE_CMD, PMBUS_WRITE_PROTECT_CMD, PMBUS_QUERY_CMD, PMBUS_SMBALERT_MASK_CMD, VOUT_COMMAND_CMD, VOUT_TRIM_CMD, VOUT_CAL_OFFSET_CMD, VOUT_MAX_CMD, VOUT_MARGIN_HIGH_CMD, VOUT_MARGIN_LOW_CMD, VOUT_TRANSITION_RATE_CMD, VOUT_DROOP_CMD, VOUT_SCALE_LOOP_CMD, VOUT_SCALE_MONITOR_CMD, 
    PMBUS_COEFFICIENTS_CMD, POUT_MAX_CMD, FAN_COMMAND_2_CMD, FAN_CONFIG_34_CMD, FAN_COMMAND_3_CMD, FAN_COMMAND_4_CMD, VOUT_OV_FAULT_LIMIT_CMD, VOUT_OV_FAULT_RESPONSE_CMD, VOUT_OV_WARN_LIMIT_CMD, VOUT_UV_WARN_LIMIT_CMD, VOUT_UV_FAULT_LIMIT_CMD, VOUT_UV_FAULT_RESPONSE_CMD, IOUT_OC_FAULT_RESPONSE_CMD, 
    IOUT_OC_LV_FAULT_LIMIT_CMD, IOUT_OC_LV_FAULT_RESPONSE_CMD, IOUT_UC_FAULT_LIMIT_CMD, IOUT_UC_FAULT_RESPONSE_CMD, OT_FAULT_LIMIT_CMD, OT_FAULT_RESPONSE_CMD, UT_WARN_LIMIT_CMD, UT_FAULT_LIMIT_CMD, UT_FAULT_RESPONSE_CMD, VIN_OV_FAULT_LIMIT_CMD, VIN_OV_FAULT_RESPONSE_CMD, VIN_OV_WARN_LIMIT_CMD, 
    VIN_UV_WARN_LIMIT_CMD, VIN_UV_FAULT_LIMIT_CMD, IIN_OC_FAULT_LIMIT_CMD, POUT_OP_WARN_LIMIT_CMD, STATUS_BYTE_CMD, STATUS_OTHER_CMD, STATUS_FAN_34_CMD, READ_VCAP_CMD, READ_FAN_SPEED_2_CMD, READ_FAN_SPEED_3_CMD, READ_FAN_SPEED_4_CMD, READ_DUTY_CYCLE_CMD, READ_FREQUENCY_CMD, PMBUS_REVISION_CMD, 
    PMBUS_MFR_ID_CMD, PMBUS_MFR_MODEL_CMD, PMBUS_MFR_REVISION_CMD, PMBUS_MFR_LOCATION_CMD, PMBUS_MFR_DATE_CMD, PMBUS_MFR_SERIAL_CMD, IC_DEVICE_ID_CMD, IC_DEVICE_REV_CMD, MFR_MAX_TEMP_3_CMD, READ_EIN_CMD, READ_EOUT_CMD};

    PSU1_CAPABILITY_Data[0] = 30;
    PSU1_CLEAR_FAULTS_Data[0] = CLEAR_FAULTS;
    PSU1_CLEAR_FAULTS_Data[1] = CLEAR_FAULTS;
    PSU1_PAGE_PLUS_WRITE_Data[0] = PAGE_PLUS_WRITE;
    PSU1_PAGE_PLUS_WRITE_Data[1] = PAGE_PLUS_WRITE;
    for (size_t i = 0; i < sizeof( CmdArrayPtr )/sizeof( CmdArrayPtr[0] ) ; i++ ) {       
        SERCOM0_I2C_WriteRead( PSU1_PMBUS_ADDR , (uint8_t*)CmdArrayPtr[i], PMbuswrLength , PSU_PMbus_Data , PMbusrdLength);
        while (SERCOM0_I2C_IsBusy( ));
        memcpy(PSU1_DataArrayPtr[i].key, PSU_PMbus_Data, PSU1_DataArrayPtr[i].value);
        PSU->psu2_table[CmdArrayPtr[i][0]].key = PSU1_DataArrayPtr[i].key;
        PSU->psu2_table[CmdArrayPtr[i][0]].cmd = CmdArrayPtr[i][0];
        memset(PSU_PMbus_Data, UN_PMBUS_STATUS, sizeof(PSU_PMbus_Data));
        if (CmdArrayPtr[i][0] == 0x8d || CmdArrayPtr[i][0] == 0x8e || CmdArrayPtr[i][0] == 0x8f)
        {
            printf("PDB I2C Master RW PSU2 temp command : 0x%x , data Byte 0: 0x%x, data Byte 1: 0x%x  \r\n", CmdArrayPtr[i][0], PSU->psu2_table[CmdArrayPtr[i][0]].key[0], PSU->psu2_table[CmdArrayPtr[i][0]].key[1]);
        }
    }
    PSU->psu2_table[CAPABILITY].key = PSU1_CAPABILITY_Data;
    PSU->psu2_table[CLEAR_FAULTS].key = PSU1_CLEAR_FAULTS_Data;
    PSU->psu2_table[PAGE_PLUS_WRITE].key = PSU1_PAGE_PLUS_WRITE_Data;
    PSU->psu2_table[CAPABILITY].cmd = CAPABILITY;
    PSU->psu2_table[CLEAR_FAULTS].cmd = CLEAR_FAULTS;
    PSU->psu2_table[PAGE_PLUS_WRITE].cmd = PAGE_PLUS_WRITE;
}

/* *****************************************************************************
 End of File
 */
